#!/usr/bin/env bash
cat <<EOF
brew-uninstall: Uninstall Homebrew and all supporting files.
EOF

if which brew; then
else
    PREFIX=/usr/local
fi

echo ---> Removing supporting files...
rm -rf "$PREFIX"/.git
rm -rf "$PREFIX"/bin
rm -rf "$PREFIX"/Library
rm -rf "$PREFIX"/share/man/man1
rm -rf "$PREFIX"/Library/LinkedKegs
rm -rf "$PREFIX"/Library/Homebrew
rm -rf "$PREFIX"/Library/Aliases
rm -rf "$PREFIX"/Library/Formula
rm -rf "$PREFIX"/Library/Contributions
rm -rf "$PREFIX"/Cellar
rm -rf /Library/Caches/Homebrew
rm -rf ~/Library/Caches/Homebrew
rm -rf ~/Library/Logs/Homebrew
