#!/usr/bin/env bash
cat <<EOF
macports-migrate: Reinstall MacPorts and all ports.

Use this script after upgrading to a new version of OS X.
See <https://trac.macports.org/wiki/Migration>

WARNING: ALL PORTS WILL BE REINSTALLED.
EOF

y_or_n "Continue?" || exit 1
cd

echo --> Writing ports list to ~/ports.txt
PORTS_LIST=ports.txt
port -qv installed > $PORTS_LIST

macports-uninstall -y
macports-install

echo --> Reinstalling ports...
curl -O \
    https://svn.macports.org/repository/macports/contrib/restore_ports/restore_ports.tcl
chmod +x restore_ports.tcl

if ./restore_ports.tcl $PORTS_LIST; then
    rm ./restore_ports.tcl
else
    cat <<EOF

Restoring ports failed.

You must install the ports you want manually. See ~/ports.txt for a list of
ports that were previously installed.

EOF
    exit 1
fi

# Local Variables:
# mode: sh
# End:
