#!/usr/bin/env sh
cat <<EOF
macports-install: install the MacPorts base system.
EOF

echo ---> Installing MacPorts...

curl -O https://distfiles.macports.org/MacPorts/MacPorts-2.2.0.tar.bz2
MACPORTS_TAR=MacPorts-2.2.0.tar.bz2
MACPORTS_SRC=MacPorts-2.2.0
tar xf $MACPORTS_TAR
(
    cd $MACPORTS_SRC
    ./configure
    make && make install
)
rm -rf $MACPORTS_SRC
rm $MACPORTS_TAR


echo ---> Updating ports list...

PATH=/opt/local/bin:$PATH
# Run twice, in case base version was updated in the first run.
port -v selfupdate
port -v selfupdate

cat <<EOF

    MacPorts installed.

EOF

# Local Variables:
# mode: sh
# End:
