#!/usr/bin/env bash

(
    if pgrep offlineimap; then
        pkill 'offlineimap$'
        # Give offlineimap time to shut down.
        sleep 10
    fi

    rm -f ~/.offlineimap/*.lock
    command -v growlnotify && growlnotify -m "Starting offlineimap"
    offlineimap
) &
