#!/usr/bin/env bash

function growl {
    command -v growlnotify && \
        growlnotify -n iTerm2 -a iTerm2 -m "$1"
}

function offlineimap_start {
    rm -f ~/.offlineimap/*.lock
    growl "Starting offlineimap..."
    if offlineimap; then
        growl "offlineimap is running."
    else
        growl "offlineimap failed."
    fi
}

function offlineimap_stop {
    if pgrep offlineimap; then
        pkill 'offlineimap$'
        # Give offlineimap time to shut down.
        sleep 10
    fi
}

################################################################################

( offlineimap_stop; offlineimap_start) > /dev/null 2>&1 &
