#!/usr/bin/env bash
#
# Migrate all installed ports.
#
# Use this script after upgrading to a new version of OS X.
#
# Source: <https://trac.macports.org/wiki/Migration>

if [ y_or_n "WARNING: MacPorts and all ports will be reinstalled. Continue?" ]; then
    echo aborted.
    exit 1
fi
cd
# Save list of ports.
port -qv installed > ports.txt
# Uninstall all ports.
port -f uninstall installed
# Clean any partially-completed builds.
port clean all
# Restore ports.
echo <<EOF
Restoring ports.
If this fails, browse ~/ports.txt and install the ports you want manually.
Most of the ports in this list will probably be dependencies and can be ignored.
EOF
curl -O \
  https://svn.macports.org/repository/macports/contrib/restore_ports/restore_ports.tcl
chmod +x restore_ports.tcl
./restore_ports.tcl ports.txt
rm ./restore_ports.tcl

# Local Variables:
# mode: sh
# End:
