#!/usr/bin/env bash
#
# Migrate all installed ports.
#
# Use this script after upgrading to a new version of OS X.
#
# Source: <https://trac.macports.org/wiki/Migration>

if [ y_or_n "WARNING: MacPorts and all ports will be reinstalled. Continue?" ]; then
    echo aborted.
    exit 1
fi
cd

# Save list of ports.
echo --> Writing ports list to ~/ports.txt
port -qv installed > ports.txt

# Uninstall all ports.
echo --> Uninstalling all ports...
port -f uninstall installed

# Clean any partially-completed builds.
echo --> Cleaning...
port clean all

# Restore ports.
echo --> Reinstalling ports...
curl -O \
    https://svn.macports.org/repository/macports/contrib/restore_ports/restore_ports.tcl
chmod +x restore_ports.tcl

if ./restore_ports.tcl ~/ports.txt; then
    rm ./restore_ports.tcl
else
    cat <<EOF
Restoring ports failed.
You must install the ports you want manually. See ~/ports.txt for a list of
ports that were previously installed. Most of the ports in this list will
probably be dependencies and can be ignored.
EOF
exit 1
fi

# Local Variables:
# mode: sh
# End:
